# Generated by Django 2.1.2 on 2018-10-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('v', 'VIDEO'), ('i', 'IMAGE')], default='i', max_length=10)),
                ('model_type', models.CharField(choices=[('w', 'WOD')], default='w', max_length=10)),
                ('model_id', models.IntegerField()),
                ('order', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'resources',
            },
        ),
        migrations.AlterIndexTogether(
            name='resource',
            index_together={('model_type', 'model_id', 'resource_type', 'order')},
        ),
    ]
