# Generated by Django 2.1.2 on 2018-10-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0003_resource_link'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together={('model_type', 'model_id', 'resource_type', 'order')},
        ),
    ]
