# Generated by Django 2.1.2 on 2018-11-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0004_auto_20181028_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='model_type',
            field=models.CharField(choices=[('g', 'GAME'), ('w', 'WOD'), ('r', 'RECORD')], default='w', max_length=10),
        ),
    ]
