# Generated by Django 2.1.2 on 2018-10-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo_image', models.ImageField(blank=True, upload_to='')),
                ('main_image', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(blank=True)),
                ('end_date', models.DateTimeField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wod_id', models.IntegerField()),
                ('team_id', models.IntegerField()),
                ('score', models.CharField(max_length=100)),
                ('point', models.PositiveSmallIntegerField()),
                ('is_ative', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'records',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('team_type', models.CharField(choices=[('individual', 'individual'), ('team', 'team')], default='team', max_length=50)),
                ('gender_type', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('mixed', 'MIXED')], default='male', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team2Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.PositiveSmallIntegerField()),
                ('game_id', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'teams_2_games',
            },
        ),
        migrations.CreateModel(
            name='WOD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wod_type', models.CharField(choices=[('amrap', 'amrap'), ('emom', 'emom'), ('for_time', 'for_time')], default='for_time', max_length=15)),
                ('description', models.TextField(blank=True)),
                ('video_link', models.URLField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'wods',
            },
        ),
        migrations.CreateModel(
            name='WOD2game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('wod_id', models.IntegerField()),
                ('order', models.PositiveSmallIntegerField()),
                ('is_ative', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'wods_2_games',
            },
        ),
        migrations.AlterUniqueTogether(
            name='wod2game',
            unique_together={('game_id', 'wod_id')},
        ),
        migrations.AlterUniqueTogether(
            name='team2game',
            unique_together={('team_id', 'game_id')},
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('wod_id', 'team_id')},
        ),
    ]
