# Generated by Django 2.1.2 on 2018-10-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='point',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='team_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='team2game',
            name='game_id',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='team2game',
            name='team_id',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='team2game',
            unique_together=set(),
        ),
    ]
