# Generated by Django 2.1.2 on 2018-10-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='logo_image',
            field=models.ImageField(blank=True, upload_to='media/games/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='media/games/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wod',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='wod',
            name='video_link',
            field=models.URLField(default=''),
        ),
    ]
