# Generated by Django 2.1.2 on 2018-10-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game2sponsor_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='WOD2Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_id', models.IntegerField()),
                ('wod_id', models.IntegerField()),
                ('order', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wods_2_competitions',
            },
        ),
        migrations.AlterField(
            model_name='wod',
            name='image_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='wod',
            name='video_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterUniqueTogether(
            name='game2sponsor',
            unique_together={('game_id', 'sponsor_id')},
        ),
        migrations.AlterUniqueTogether(
            name='wod2competition',
            unique_together={('competition_id', 'wod_id', 'order')},
        ),
    ]
