# Generated by Django 2.1.2 on 2018-11-03 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20181029_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='wod',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='wod',
            name='video_link',
        ),
    ]
