# Generated by Django 2.1.2 on 2018-12-28 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20181103_0332'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sponsor',
        ),
    ]
