# Generated by Django 2.1.2 on 2018-12-29 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20181229_0724'),
        ('games', '0009_delete_sponsor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
