# Generated by Django 2.1.5 on 2019-01-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('game_id', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo_image', models.ImageField(blank=True, upload_to='games/')),
                ('description', models.TextField(blank=True, default='')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='Game2Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(db_index=True)),
                ('sponsor_id', models.IntegerField(db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'games_2_sponsors',
            },
        ),
        migrations.CreateModel(
            name='Team2Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('competition_id', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teams_2_competitions',
            },
        ),
        migrations.CreateModel(
            name='Team2Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.PositiveSmallIntegerField(db_index=True)),
                ('game_id', models.PositiveSmallIntegerField(db_index=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teams_2_games',
            },
        ),
        migrations.CreateModel(
            name='WOD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wod_type', models.CharField(choices=[('amrap', 'amrap'), ('emom', 'emom'), ('for_time', 'for_time')], default='for_time', max_length=15)),
                ('description', models.TextField(blank=True, default='')),
                ('competition_id', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wods',
            },
        ),
        migrations.CreateModel(
            name='WOD2Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_id', models.IntegerField()),
                ('wod_id', models.IntegerField()),
                ('order', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wods_2_competitions',
            },
        ),
        migrations.CreateModel(
            name='WOD2Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('wod_id', models.IntegerField()),
                ('order', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wods_2_games',
            },
        ),
        migrations.AlterUniqueTogether(
            name='wod2game',
            unique_together={('game_id', 'wod_id', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='wod2competition',
            unique_together={('competition_id', 'wod_id', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='team2game',
            unique_together={('team_id', 'game_id')},
        ),
        migrations.AlterUniqueTogether(
            name='game2sponsor',
            unique_together={('game_id', 'sponsor_id')},
        ),
    ]
