# Generated by Django 2.1.4 on 2018-12-29 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20181229_0835'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sponsor',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
