# Generated by Django 2.1.4 on 2018-12-29 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20181229_0835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
